# Generated by Django 5.0.6 on 2024-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modifier',
            name='abbr',
            field=models.CharField(default='C', max_length=4),
            preserve_default=False,
        ),
    ]
