# Generated by Django 5.0.6 on 2024-07-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_combo_outdated_modifier_abbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='average_damage',
            field=models.IntegerField(default=0),
        ),
    ]
