# Generated by Django 5.0.6 on 2024-07-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_combo_average_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='attacks', to='main.modifier'),
        ),
    ]
