# Generated by Django 5.0.6 on 2024-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attack_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='stop_damage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
