# Generated by Django 5.0.6 on 2024-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_combo_stop_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='attacks',
            field=models.ManyToManyField(blank=True, related_name='combos', to='main.attack'),
        ),
    ]
