# Generated by Django 5.0.6 on 2024-10-08 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_combo_attacks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ['-usability']},
        ),
        migrations.AddField(
            model_name='legend',
            name='dexterity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='combo',
            name='dexterity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
