# Generated by Django 5.0.6 on 2024-10-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='legend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combos', to='main.legend'),
        ),
    ]
