# Generated by Django 5.0.6 on 2024-10-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_combo_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_movement',
            field=models.BooleanField(default=False),
        ),
    ]
