# Generated by Django 5.0.6 on 2024-10-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_move_is_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='main.combo'),
        ),
    ]
