# Generated by Django 5.0.6 on 2024-10-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_combo_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_signature',
            field=models.BooleanField(default=False),
        ),
    ]
