# Generated by Django 5.0.6 on 2024-10-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_move_is_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
