# Generated by Django 5.0.6 on 2024-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_move_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='html_title',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
